// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4662.Tank2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4662.Tank2016.Robot;
//import org.usfirst.frc4662.Tank2016.RobotMap;

//import com.ni.vision.NIVision;

/**
 *
 */
public class CameraToggle extends Command {

    public CameraToggle() {

    }

    // Called just before this Command runs the first time
    protected void initialize() {
    
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(Robot.currCam == Robot.loaderCam){
    		Robot.currCam.stopCapture();
    		Robot.currCam = Robot.shooterCam;
    		Robot.currCam.startCapture();
    		
    	}else if (Robot.currCam == Robot.shooterCam){
    		Robot.currCam.stopCapture();
    		Robot.currCam = Robot.loaderCam;
    		Robot.currCam.startCapture();
    	}
   	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
